### ISSUE TITLE
Getting the error "num_samples=0"

### ISSUE THREAD

**Issue by QLaHPD** [YannDubs/disentangling-vae#51]
18:49:06 INFO - main: Root directory for saving and loading experiments: results\test01
Traceback (most recent call last):
  File "main.py", line 252, in <module>
    main(args)
  File "main.py", line 199, in main
    logger=logger)
  File "R:\disentangling-vae-master\utils\datasets.py", line 71, in get_dataloaders
    **kwargs)
  File "B:\Program_Files\Anaconda3\envs\dis-VAE\lib\site-packages\torch\utils\data\dataloader.py", line 802, in \_\_init\_\_
    sampler = RandomSampler(dataset)
  File "B:\Program_Files\Anaconda3\envs\dis-VAE\lib\site-packages\torch\utils\data\sampler.py", line 64, in \_\_init\_\_
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integeral value, but got num_samples=0

Is there any place to set the value to > 0

**Comment by YannDubs** [comment]
What command are you running? It seems that you are trying to plot or train something empty

**Comment by QLaHPD** [comment]
python main.py test01 -d R:\disentangling-vae-master\data\celeba
I changed the __--dataset__ to the correct path where are 2000 JPG 128x128 test images.

**Comment by YannDubs** [comment]
Dataset is not a path flag, but a flag with which to chose chose one of the predefined datasets (cf. The cli helper). If you want to use your own dataset you have to define a class for it. 
I’m surprised you were able to give a path, it should only let you give one of the predefined datasets.

**Comment by QLaHPD** [comment]
How I should do this?

**Comment by YannDubs** [comment]
You probably want to look at basic dataset tutorials for Pytorch. It depends how exactly your data is. 

If it is under a simple format, with all images in one directory then you probably want to create a new object for your dataset which closely follows the [celeba one](https://github.com/YannDubs/disentangling-vae/blob/master/utils/datasets.py#L216). 

as it is already downloaded you can use a placeholder for the download method. e.g. 
```
def download(self):
        return
```
