### ISSUE TITLE
Doubts about the calculation of H_z

### ISSUE THREAD

**Issue by erow** [YannDubs/disentangling-vae#59]
The problem is here `log_q_zCx = log_density_gaussian(samples_zCx[..., idcs],
                                                 mean[..., idcs],
                                                 log_var[..., idcs])`.

`q_zCx` is a density function, which should be integrated.
Therefore, I write a probability implement. `q_zCx` calculates P(a<=z<=b|x).
```
def erf(x):
    a1 = 0.278393
    a2 = 0.230389
    a3 = 0.000972
    a4 = 0.078108
    s = torch.sign(x)
    x = x.abs()
    e = 1-1/(1 + a1*x + a2*x**2 + a3*x**3 + a4*x**4)**4
    return s*e


def Gab(a,b,mu,sigma):
    '''
    the probability of z belonging to [a,b]
    :param a:
    :param b:
    :param mu:
    :param sigma:
    :return:
    '''
    inverse_sigma = 1/(math.sqrt(2)*sigma)
    return 0.5 * (erf((b-mu)*inverse_sigma)-
                     erf((a-mu)*inverse_sigma))

samples,params,recons,labels = evaluator.compute(test_loader)

N_x_samples = 1000
M_z_samples = 100
mu,logvar = params
mu,logvar = mu[:N_x_samples],logvar[:N_x_samples]

mu =mu.view(1,N_x_samples,dim).repeat(M_z_samples,1,1)
logvar =logvar.view(1,N_x_samples,dim).repeat(M_z_samples,1,1)

l = torch.linspace(-3,3,M_z_samples+1)
d = l[1]-l[0]
a = l[:-1].cuda()
b = l[1:].cuda()

a = a.reshape(-1,1,1).expand(M_z_samples,N_x_samples,dim)
b = b.reshape(-1,1,1).expand(M_z_samples,N_x_samples,dim)


q_zCx = Gab(a,b,mu,torch.exp(0.5*logvar))
q_z = q_zCx.mean(1)
H_z = (-q_z*(q_z/d).log()).sum(0) ```

**Comment by erow** [comment]
To simplify this issue, assume 'z' obeys a standard normal distribution. 
So H(z) = integrate(-p(z)*log(p(z)),{z,-inf,inf}). But here you sample 'z' and get some points. The corresponding calculation is sum(-p(zi)*log(p(zi)),{i,1,N}), which is not right.
And a better way is  sum(-p(zi)*0.1*log(p(zi)),{zi,-4,4,0.1}), zi is a set of linspace -4, -3.9, ..., 4

**Comment by YannDubs** [comment]
It's not a sum but a mean because its divide by the number of samples 

https://github.com/YannDubs/disentangling-vae/blob/6a007067af1729ff556fa0b003096d200f80cb9f/disvae/evaluate.py#L295

This is simply a Monte Carlo approximation of the integral you are talking about. Using a grid as you suggest suffers from 2 issues:
- it  scales exponentially with the number of dimensions
- it requires evaluating p(z) multiple times (here we are not doing any additional evaluations, simply using the samples we already have access to)

**Comment by erow** [comment]
Better to make an error analysis. My implementation refers to A.10(https://arxiv.org/abs/1908.09961).
The entropy of standard normal distribution is `0.5*(math.log(2*math.pi)+1)=1.418`, however, this approach is 0.9189.
```
param=(torch.zeros(100,1),torch.zeros(100,1))
samples_zCx=self.model.reparameterize(*param)
len_dataset, latent_dim = samples_zCx.shape

# marginal entropy H(z_j)
H_z = self._estimate_latent_entropies(samples_zCx, param)
```

**Comment by YannDubs** [comment]
we are exaxtly doing what is called "estimating by sampling" in the paper you sent. They even explicitly say that "estimation by quantization" that you said only works for scalars z (this is actually not true but it becomes computationally intractable in higher dimensions)

An error analysis on one try does not make sense as it's a stochastic approximation. Can you please run the same code but average over ~10000 trials and see whether the average is close to H_z ?

**Comment by erow** [comment]
But our goal is to estimate z_j instead of z. I have to say quantization has a lower error and compute-time is acceptable.
