### ISSUE TITLE
PlotNeuralNet Code

### ISSUE THREAD

**Issue by ericluo04** [YannDubs/disentangling-vae#65]
Hello! I was kindly wondering if you could share your PlotNeuralNet code (which is what I presume you used to generate [this](https://raw.githubusercontent.com/YannDubs/disentangling-vae/master/doc/imgs/architecture.png)). I would really appreciate it! To my knowledge, there aren't any VAE visualization examples for this online, so I imagine it would be very helpful for others too.

**Comment by linesd** [comment]
Hello, indeed PlotNeuralNet was used to generate the architecture diagram. I checked but unfortunately I deleted the code to produce it - but if I remember correctly it was straight forward and mainly used already existing blocks from PlotNeuralNet with minor adjustments.

**Comment by ericluo04** [comment]
Ohh no problem - thanks for checking anyways!
