### ISSUE TITLE
How can I apply it to my own dataset？

### ISSUE THREAD

**Issue by hxhebit** [YannDubs/disentangling-vae#73]

**Comment by hxhebit** [comment]
The dataset structure：

|- class 1
|        |-  class a
|        |       |- item 1
|        |       |- item 2
|        |       |.....
|        |- class b
|        |- class c
|        |......
| - class 2
| ......

**Comment by YannDubs** [comment]
you have to use a pytorch dataloader. Example: https://github.com/YannDubs/disentangling-vae/blob/master/utils/datasets.py#L213 to see what you have to return
